vile:
  ignore:
    - ".*"
    - bin
    - coverage
    - doc
    - "*.json"
    - lib
    - LICENSE
    - "*.lock"
    - "*.log"
    - "*.md"
    - node_modules
    - src/@types
    - tags
    - test/fixtures
    - test/mocha.opts
    - tmp
    - vendor
    - "*.yml"

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs:
      - src
      - typings
      - node_modules
      - coverage
      - tmp
    ignore_deps:
      - bluebird
      - mocha
      - babel-cli
      - coffee-script
      - istanbul
      - release-it
      - typescript
      - wrench
      - pryjs
      - shelljs
      - "vile-**"
