version: "#{build}"

os: Visual Studio 2017

cache:
  - node_modules

environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8

matrix:
  fast_finish: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

branches:
  only:
    - master

skip_tags: true

clone_depth: 10

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - ver && node --version && npm --version
  - npm i

test_script:
  - npm run compile
  - npm run compile-dev
  - npm test
