version: "#{build}"

os: Visual Studio 2015

cache:
  - node_modules

environment:
  matrix:
    - nodejs_version: 4
      npm_version: 2.x.x
    - nodejs_version: 4
      npm_version: 3.x.x
    - nodejs_version: 4
      npm_version: 4.x.x
    - nodejs_version: 6
      npm_version: 2.x.x
    - nodejs_version: 6
      npm_version: 3.x.x
    - nodejs_version: 6
      npm_version: 4.x.x

matrix:
  fast_finish: true

platform:
  - x86
  - x64

init:
  - git config --global core.autocrlf input

branches:
  only:
    - master

skip_tags: true

clone_depth: 10

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: npm install -g npm@$env:npm_version
  - ver && node --version && npm --version
  - npm i

test_script:
  - npm run compile
  - npm run compile-dev
  - npm test
